
CREATE TABLE bookmarks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    description TEXT NOT NULL,
    rating INTEGER NOT NULL
);

-- CREATE TYPE rating_range AS ENUM (
--     '1','2','3','4','5'
-- );

-- ALTER TABLE bookmarks
--     ADD COLUMN rating rating_range NOT NULL;